version: '3.7'

services:
  mysql:
    build: .
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: database_demo
      MYSQL_USER: 123
      MYSQL_PASSWORD: 112233
      MYSQL_ROOT_PASSWORD: 123456789q
